### ISSUE TITLE
[BUG]: Visible Traceback on Linux when Exiting

### ISSUE THREAD

**Issue by mad-moo** [rio-labs/rio#165]
### Describe the bug

When closing an app with `rio run` by `Ctrl+C` sometimes, but not always, an ugly traceback shows up in the terminal. Everything works fine, but this is rather confusing if you don't know that it can be safely ignored. This has been seen on Linux, but never on Windows. Status on Mac is unknown.

```
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jakob/Local/rio/.venv/lib/python3.10/site-packages/starlette/routing.py", line 732, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "/home/jakob/.rye/py/cpython@3.10.13/lib/python3.10/contextlib.py", line 206, in __aexit__
    await anext(self.gen)
  File "/home/jakob/Local/rio/rio/app_server/fastapi_server.py", line 359, in _lifespan
    await self._on_close()
  File "/home/jakob/Local/rio/rio/app_server/abstract_app_server.py", line 101, in _on_close
    results = await asyncio.gather(
asyncio.exceptions.CancelledError
```

### Steps to Reproduce

- Run an app using `rio run`
- Ctrl-C

Retry a couple times if it doesn't happen. Seems to be more reliable after the app has reloaded.

### Operating System

Linux

### What device are you using?

Desktop

**Comment by mad-moo** [comment]
This is temporarily worked around by shielding the canceled tasks. In `abstract_app_server.py`:

```py
        results = await asyncio.gather(
            # On Linux, some of these tasks are sometimes canceled, resulting in
            # a visible, ugly traceback in the console. Debugging has been
            # fruitless so far, hence the `asyncio.shield` hack.
            *(
                asyncio.shield(sess._close(close_remote_session=True))
                for sess in self.sessions
            ),
            return_exceptions=True,
        )
```
