### ISSUE TITLE
Add Instructions for Bundling (pyinstaller, py2exe or similar)

### ISSUE THREAD

**Issue by mad-moo** [rio-labs/rio#202]
If you're familiar with `pyinstaller` or similar, this issue is for you!

Given Rio's ability to create desktop apps, it would be very nice to have a tried and true method for bundling apps made with Rio. Create an app, turn it into an exe, and provide detailed instructions (and maybe a sample configuration file) for creating executables.

**Comment by iwr-redmond** [comment]
You may wish to consider [Briefcase](https://github.com/beeware/briefcase), which is part of the Beeware suite. It largely eschews binary file compilation, which can trigger malware scanners, and is well-integrated with platform-specific application distribution mechanisms (Windows Installer, OS X disk image, deb/rpm).

A tutorial is available [here](https://docs.beeware.org/en/latest/tutorial/tutorial-3.html).

**Comment by gsal** [comment]
As a first-timer, the Briefcase instructions are not enough, for a couple of reasons:

1. I started my Rio project according to Rio instructions: `rio new`.  This creates a scaffolding different to the one from Briefcase, no `src` directory, no `pyproject.toml` file.  O.k., no problem, read docs...one can use `briefcase convert` after the fact. 
2. But, it seems a Rio program has its own particular way of starting execution...does Briefcase know about that?  I just tried Briefcase, it created an *.exe, and a blank window comes up and then goes away....How do I tell Briefcase how to run the Rio program? 

What I would really want to do, at this time, is to use Briefcase to package the Rio app for deployment into an Android phone; tried that, got an error: 

```
Collecting watchfiles~=0.21
  Using cached watchfiles-0.24.0.tar.gz (37 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
    Preparing wheel metadata: started
    Preparing wheel metadata: finished with status 'error'
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\salazag\programming\rio\palabroso\build\palabroso\android\gradle\app\build\python\env\debug\Scripts\python.exe' 'C:\Users\salazag\programming\rio\palabroso\build\palabroso\android\gradle\app\build\python\env\debug\lib\site-packages\pip\_vendor\pep517\_in_process.py' prepare_metadata_for_build_wheel 'C:\Users\salazag\AppData\Local\Temp\tmpitt16g25'
         cwd: C:\Users\salazag\AppData\Local\Temp\pip-install-xctuhmyl\watchfiles
    Complete output (20 lines):
    Checking for Rust toolchain....
    Running `maturin pep517 write-dist-info --metadata-directory C:\Users\salazag\AppData\Local\Temp\pip-modern-metadata-9nrwd2wl --interpreter C:\Users\salazag\programming\rio\palabroso\build\palabroso\android\gradle\app\build\python\env\debug\Scripts\python.exe`
    Traceback (most recent call last):
      File "C:\Users\salazag\programming\rio\palabroso\build\palabroso\android\gradle\app\build\python\env\debug\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 280, in <module>
        main()
      File "C:\Users\salazag\programming\rio\palabroso\build\palabroso\android\gradle\app\build\python\env\debug\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 263, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
      File "C:\Users\salazag\programming\rio\palabroso\build\palabroso\android\gradle\app\build\python\env\debug\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 133, in prepare_metadata_for_build_wheel
        return hook(metadata_directory, config_settings)
      File "C:\Users\salazag\AppData\Local\Temp\pip-build-env-whr84wq6\overlay\Lib\site-packages\maturin\__init__.py", line 203, in prepare_metadata_for_build_wheel
        _output = subprocess.check_output(command)
      File "C:\programs\gttools\python3\3.10.5\lib\subprocess.py", line 420, in check_output
        return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
      File "C:\programs\gttools\python3\3.10.5\lib\subprocess.py", line 501, in run
        with Popen(*popenargs, **kwargs) as process:
      File "C:\programs\gttools\python3\3.10.5\lib\subprocess.py", line 969, in __init__
        self._execute_child(args, executable, preexec_fn, close_fds,
      File "C:\programs\gttools\python3\3.10.5\lib\subprocess.py", line 1438, in _execute_child
        hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
    FileNotFoundError: [WinError 2] The system cannot find the file specified
    ----------------------------------------
ERROR: Failed to install watchfiles~=0.21 from https://files.pythonhosted.org/packages/c8/27/2ba23c8cc85796e2d41976439b08d52f691655fdb9401362099502d1f0cf/watchfiles-0.24.0.tar.gz#sha256=afb72325b74fa7a428c009c1b8be4b4d7c2afedafb2982827ef2156646df2fe1 (from rio-ui==0.11.1->-r requirements.txt (line 2)).
For assistance, please raise an issue at https://github.com/chaquo/chaquopy/issues.
Chaquopy: Exit status 1
```

Sorry, I don't mean to hijack this thread; hopefully the issue title will be satisfied after the error above.

**Comment by gsal** [comment]
After packaging the Rio app with Briefcase, and launching it, this is the error message: 

```
Traceback (most recent call last):
  File "runpy.py", line 110, in _get_module_details
  File "\app\myapp\__init__.py", line 6, in <module>
    import rio
  File "\app_packages\rio\__init__.py", line 20, in <module>
    from .app import *
  File "\app_packages\rio\app.py", line 30, in <module>
    from .app_server import fastapi_server
  File "\app_packages\rio\app_server\__init__.py", line 1, in <module>
    from .abstract_app_server import *
  File "\app_packages\rio\app_server\abstract_app_server.py", line 22, in <module>
    from .. import (
  File "\app_packages\rio\session.py", line 21, in <module>
    import revel
  File "\app_packages\revel\__init__.py", line 3, in <module>
    from .cli_app import App, Parameter
  File "\app_packages\revel\cli_app.py", line 7, in <module>
    from . import argument_parser, common
  File "\app_packages\revel\argument_parser.py", line 10, in <module>
    from . import common, legacy, menu
  File "\app_packages\revel\legacy.py", line 1158, in <module>
    _set_cursor(False)
  File "\app_packages\revel\legacy.py", line 1144, in _set_cursor
    sys.stdout.write("\033[?25h" if enable_cursor else "\033[?25l")
AttributeError: 'NoneType' object has no attribute 'write'

```

**Comment by iwr-redmond** [comment]
Does Rio support Android in app mode? I don't recall reading this anywhere.

The entry point is probably [run_as_web_server](https://github.com/rio-labs/rio/blob/f482fab7267f365c970c4cf68c1d00e973981201/rio/app.py#L811).

**Comment by gsal** [comment]
Oh. I guess that's the question. 

Last month, I thought of implementing a game.  While looking for an easy framework, I run into BeeWare; and, although I was able to put something together really quick and even put it in my cellphone, I couldn't customize the app much...it was limiting.

So, I started to write the same game with Rio...so much better; but, granted, I was coming from the assumption that I was going to be able to put it in my cellphone. It did not occur to me to stop and ask. 

Currently, I have the app in app mode; I wonder if switching to website would make a difference? I mean, browser technology should be supported just the same regardless of the platform, shouldn't it?

**Comment by iwr-redmond** [comment]
Rio uses [Pyside6 via Pywebview](https://github.com/rio-labs/rio/blob/f482fab7267f365c970c4cf68c1d00e973981201/rio/webview_shim.py#L40) for app mode, and Pyside6 is [not available](https://pypi.org/project/PySide6/#files) for Android. However, all this really does is start the web server and open a desktop browser.

Pywebview does [support](https://github.com/r0x0r/pywebview/blob/master/webview/platforms/android.py) Android via Kivy, but this implementation is currently unsupported in Rio. You could probably adapt the [Flask example](https://github.com/r0x0r/pywebview/tree/21a609b3af4cc13d2224b812903c5f4794ab3d03/examples/flask_app/src/backend), replacing Flask with Rio.

**Comment by Aran-Fey** [comment]
I believe that pywebview treats PySide as the preferred backend, but automatically chooses a different one if PySide isn't available. So it should work on android. The entry point would be `App.run_in_window()`.

**Comment by iwr-redmond** [comment]
I reckon [line 43](https://github.com/rio-labs/rio/blob/f482fab7267f365c970c4cf68c1d00e973981201/rio/webview_shim.py#L43) needs to be amended to do a platform check, and skip the assert statement if the operating system isn't Windows, Linux, or macOS.

**Comment by iwr-redmond** [comment]
The other issue is that [watchfiles](https://github.com/rio-labs/rio/blob/f482fab7267f365c970c4cf68c1d00e973981201/pyproject.toml#L32) doesn't have prebuilt wheels for Android. The Readme file [says](https://github.com/samuelcolvin/watchfiles?tab=readme-ov-file#installation):

> You can install from source which requires Rust stable to be installed.

**Comment by gsal** [comment]
Either when installing Briefcase or most probably when running it for the first time, it complained about missing Rust; so, I installed Rust, which in turn first complained about missing Visual Studio libraries....so, I have VS libs, Rust, Briefcase.

**Comment by iwr-redmond** [comment]
Make sure you have the directories containing cl.exe and rustc.exe in your PATH. In the absence of this setting, Python may not be able to access either tool.

**Comment by gsal** [comment]
Well, I tried. 

- downloaded watchfiles
- attempted to `make lint`
- kept asking for things: uv, pre-commit, ruff, mypy
- at this time I am stuck at: 

```
$ make lint
ruff check watchfiles tests
All checks passed!
ruff format --check watchfiles tests
17 files already formatted
cargo fmt --version
rustfmt 1.8.0-stable (05f9846f89 2025-03-31)
cargo fmt --all -- --check
cargo clippy --version
clippy 0.1.86 (05f9846f89 2025-03-31)
cargo clippy -- -D warnings
    Updating crates.io index
     Locking 6 packages to latest compatible versions
    Updating pyo3 v0.23.1 -> v0.23.5 (available: v0.24.1)
    Updating pyo3-build-config v0.23.1 -> v0.23.5
    Updating pyo3-ffi v0.23.1 -> v0.23.5
    Updating pyo3-macros v0.23.1 -> v0.23.5
    Updating pyo3-macros-backend v0.23.1 -> v0.23.5
    Updating python3-dll-a v0.2.10 -> v0.2.13
  Downloaded pyo3-build-config v0.23.5
  Downloaded pyo3-macros v0.23.5
  Downloaded pyo3-macros-backend v0.23.5
  Downloaded pyo3-ffi v0.23.5
  Downloaded pyo3 v0.23.5
  Downloaded 5 crates (1.3 MB) in 1.11s (largest was `pyo3` at 1.1 MB)
   Compiling python3-dll-a v0.2.13
   Compiling pyo3-build-config v0.23.5
   Compiling pyo3-ffi v0.23.5
   Compiling pyo3-macros-backend v0.23.5
   Compiling pyo3 v0.23.5
   Compiling pyo3-macros v0.23.5
    Checking watchfiles_rust_notify v1.0.0 (C:\Users\myuserid\programming\rio\wfiles\watchfiles-1.0.0)
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 10.28s
$ make mypy
mypy watchfiles
watchfiles\run.py:339: error: Module has no attribute "SIGKILL"; maybe "SIGILL"?  [attr-defined]
watchfiles\run.py:401: error: Module has no attribute "ttyname"  [attr-defined]
Found 2 errors in 1 file (checked 8 source files)
make: *** [Makefile:47: mypy] Error 1
```

**Comment by iwr-redmond** [comment]
I suggest filing a bug in the [watchfiles repository](https://github.com/samuelcolvin/watchfiles/).

**Comment by Aran-Fey** [comment]
`watchfiles` is only needed for the automatic reloading of `rio run`, so it can theoretically be omitted. Unfortunately there doesn't seem to be an easy way to ignore one specific dependency. You would have to install rio with `--no-deps` and then manually install all the remaining dependencies.

**Comment by gsal** [comment]
Hhhmmm, that does not seem to cut it.  It looks like Briefcase is doing its own dependency resolution and grabbing watchfiles, anyway, based on Rio's own `requirements.txt` file: 

![Image](https://github.com/user-attachments/assets/2e84985b-0980-4537-9e14-56a6ae156bcd)

**Comment by gsal** [comment]
It's as if I need a version of Rio that truly does not include watchfiles as a dependency....and who knows what else  ;-)
